config:
    partial_parse: true
jaffle_shop:
  target: fabric-dev
  outputs:
    fabric-dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: "x6eps4xrq2xudenlfv6naeo3i4-nkbn5kalhahujjtdo4w6y2qbeu.msit-datawarehouse.fabric.microsoft.com"
      port: 1433
      database: "postgres-warehouse"
      schema: dbo
      authentication: ActiveDirectoryPassword
      user: "{{ env_var('USERNAME') }}"
      password: "{{ env_var('PASSWORD') }}"
