config:
    partial_parse: true
jaffle_shop:
  target: fabric-dev
  outputs:
    fabric-dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: "lfq2eq4ojyvejh44zn5bgsa5ja-dggi7l3kemauzowjworwbxdh2i.msit-datawarehouse.fabric.microsoft.com"
      port: 1433
      database: "contoso-warehouse"
      schema: dbo
      authentication: ActiveDirectoryPassword
      user: Admin@FabricMSIT.onmicrosoft.com
      password: Y1atqV#to)[v;^z